apiVersion: apps/v1
kind: Deployment
metadata:
  name: conv-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      components: backend
  template:
    metadata:
      labels:
        components: backend
    spec:
      containers:
      - name: conv-api
        image: antonlarichev/conv-api:1.0
        resources:
          limits:
            memory: "500Mi"
            cpu: "200m"
        ports:
        - containerPort: 3000
        env:
          - name: AMQP_EXCHANGE
            value: test          
          - name: AMQP_USER
            valueFrom:
              secretKeyRef:
                name: rabbit-secret
                key: SEED_USERNAME
          - name: AMQP_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rabbit-secret
                key: SEED_USER_PASSWORD
          - name: AMQP_HOSTNAME
            value: rabbit-clusterip
          - name: AMQP_QUEUE
            value: test       
        volumeMounts:
          - name: api-data
            mountPath: /opt/app/uploads
      volumes: 
        - name: api-data
          persistentVolumeClaim:
            claimName: api-pvc