apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-rabbit
spec:
  replicas: 1
  selector:
    matchLabels:
      components: rabbitmq
  template:
    metadata:
      labels:
        components: rabbitmq
    spec:      
      containers:
      - name: rabbitmq
        image: rabbitmq
        resources:
          limits:
            memory: "500Mi"
            cpu: "300m"
        ports:
        - containerPort: 5672
          protocol: TCP
        - containerPort: 15672
          protocol: TCP
        env:        
          - name: SEED_USERNAME
            valueFrom: 
              secretKeyRef: 
                name: rabbit-secret
                key: SEED_USERNAME                
          - name: SEED_USER_PASSWORD
            valueFrom: 
              secretKeyRef: 
                name: rabbit-secret
                key: SEED_USER_PASSWORD    
        volumeMounts:
          - name: rabbit-data
            mountPath: /var/lib/rabbitmq
            subPath: data
      volumes: 
        - name: rabbit-data
          persistentVolumeClaim:
            claimName: rabbit-pvc
