apiVersion: v1
kind: Service
metadata:
  name: rabbit-clusterip
spec:
  selector:
    components: rabbitmq
  ports:
  - name: amqp-port
    port: 5672
    protocol: TCP
  - name: management-port
    port: 15672
    protocol: TCP