apiVersion: apps/v1
kind: Deployment
metadata:
  name: conv-service
spec:
  selector:
    matchLabels:
      components: conv-service-deployment
  template:
    metadata:
      labels:
        components: conv-service
    spec:
      containers:
      - name: conv-service
        image: antonlarichev/conv-service:1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        ports:
        - containerPort: 8080
        env:
          - name: AMQP_EXCHANGE
            value: test          
          - name: AMQP_USER
            valueFrom:
              secretKeyRef:
                name: rabbit-secret
                key: SEED_USERNAME
          - name: AMQP_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rabbit-secret
                key: SEED_USER_PASSWORD
          - name: AMQP_HOSTNAME
            value: rabbit-clusterip
          - name: AMQP_QUEUE
            value: test
          
